README.md
poetry.lock
pyproject.toml

chore: support python 3.10

---

.github/workflows/ci.yml
.github/workflows/python-package.yml
Makefile
poetry.lock
pyproject.toml

- fix python version spec
- add initial CI workflow

chore: initial CI workflow

---

numalogic/models/autoencoder/pipeline.py
numalogic/models/autoencoder/variants/__init__.py
numalogic/models/autoencoder/variants/conv.py
numalogic/models/autoencoder/variants/lstm.py
numalogic/models/autoencoder/variants/transformer.py
numalogic/models/autoencoder/variants/vanilla.py
numalogic/registry/__init__.py
numalogic/registry/mlflow_registry.py
numalogic/tests/models/autoencoder/test_pipeline.py
numalogic/tests/models/autoencoder/variants/test_transformers.py
numalogic/tests/registry/test_mlflow_registry.py
pyproject.toml

- Added new Transformers model
- Added docstring for models and pipeline
- Refactored doctring formatting to follow google format
- Rename mlflow.py to mlflow_registry.py
- Added new testcases for mlflow_registry

feat: add transformers model

---

.github/workflows/pypi.yml
.github/workflows/release.yml
README.md

- add auto pypi publish workflow
- add auto release generation workflow
- add coverage % badge in README

workflows: add pypi publish and auto release generation

---

README.md

[Chore] Update README

---

mkdocs.yml

chore: use separated tracking id

---

.github/workflows/gh-pages.yaml
docs/CNAME

Signed-off-by: Derek Wang <whynowy@gmail.com>

chore: move CNAME to GH action

---

USERS.md

Signed-off-by: Edward Lee <edward_lee@intuit.com>

docs:Add USERS.md

---

numalogic/models/autoencoder/pipeline.py
numalogic/tests/models/autoencoder/test_pipeline.py
pyproject.toml

Added a a new parameter resume training. This will take account whether optimizer state dict has to be stored or not.

add: resume training parameter

---

mkdocs.yml

docs: add the link to numaproj

---

numalogic/models/autoencoder/pipeline.py
numalogic/tests/models/autoencoder/test_pipeline.py

* updates AutoencoderPipeline.fit to log the mean of the batches for each epoch
* added a trap for invalid num_epochs
* added a test for invalid epoch catching

Autoencoder logged loss mean

---

docs/quick-start.md

Signed-off-by: Vigith Maurice <vigith@gmail.com>

doc: typos

---

docs/data-generator.md
docs/quick-start.md

Signed-off-by: nkoppisetty <nandita.iitkgp@gmail.com>
Updating links in quick-start

docs: updating links

---

docs/quick-start.md
examples/numalogic-simple-pipeline/Dockerfile
examples/numalogic-simple-pipeline/numa-pl.yaml
examples/numalogic-simple-pipeline/simple-numalogic-pl.yaml
examples/numalogic-simple-pipeline/src/udf/postprocess.py
examples/numalogic-simple-pipeline/src/udf/train.py
examples/numalogic-simple-pipeline/src/utils.py

- fix quick start docs with numaflow
- fix docker image name in pipeline yaml
- fix flake8 errors in examples dir
closes #28

docs: fix numaflow quickstart

---

docs/quick-start.md

Fixing a small bug in the quick start docs.

docs: fix typo

---

docs/quick-start.md

mention namespace name when applying the pipeline

fix_readme: mention namespace name when applying the pipeline

---

poetry.lock
pyproject.toml

chore: bump to v0.2.7 for new release

---

.flake8
examples/numalogic-simple-pipeline/Dockerfile
examples/numalogic-simple-pipeline/numa-pl.yaml
examples/numalogic-simple-pipeline/poetry.lock
examples/numalogic-simple-pipeline/pyproject.toml
examples/numalogic-simple-pipeline/src/udf/inference.py
examples/numalogic-simple-pipeline/src/utils.py
numalogic/registry/mlflow_registry.py
numalogic/tests/registry/_mlflow_utils.py
numalogic/tests/registry/test_mlflow_registry.py
poetry.lock
pyproject.toml

1. Fix: mlflow test cases for numalogic 0.3 release
2. Fix: Flake8 file.
3. Add `mlflow-skinny` and `mlflow` to the extras dependency.
4. Add: multistage docker file.
TODO [@ab93 ]
1. Use Updated DockerImage in the pipeline example.
2. Update the toml and poetry file.
3. Update starter docs.

fix: fix mlflow test cases

---

examples/numalogic-simple-pipeline/src/udf/inference.py
examples/numalogic-simple-pipeline/src/udf/train.py
examples/numalogic-simple-pipeline/src/utils.py
numalogic/models/autoencoder/pipeline.py
numalogic/models/threshold/_std.py
numalogic/registry/artifact.py
numalogic/registry/mlflow_registry.py
pyproject.toml

fix pipeline for 0.3 release. (loading and saving of threshold models, modified mlflow api calls).

fix: fix pipeline for 0.3 release

---

CHANGELOG.md
Makefile
docs/quick-start.md
examples/numalogic-simple-pipeline/.dockerignore
examples/numalogic-simple-pipeline/Dockerfile
examples/numalogic-simple-pipeline/numa-pl.yaml
poetry.lock
pyproject.toml

Merging `main` --> `release-0.3`

Merge main 0.3

---

README.md
docs/quick-start.md
numalogic/models/autoencoder/trainer.py

docs: update quickstart

---

poetry.lock
pyproject.toml

fix: pin protobuf to v3.20 for pytorch-lightning

---

numalogic/models/autoencoder/trainer.py
numalogic/models/autoencoder/variants/conv.py
numalogic/models/autoencoder/variants/lstm.py
numalogic/models/autoencoder/variants/transformer.py
numalogic/models/autoencoder/variants/vanilla.py
numalogic/tools/data.py
numalogic/tools/exceptions.py
pyproject.toml
tests/models/autoencoder/test_trainer.py
tests/tools/test_data.py

* Fixes unbatching error on predict
* Fixes issue with Sparse autoencoders, when there is a device type mismatch

fix: unbatch error on certain cases

---

.codecov.yml
.github/CODEOWNERS
Makefile
numalogic/__init__.py
numalogic/_constants.py
numalogic/models/autoencoder/__init__.py
numalogic/models/autoencoder/base.py
numalogic/models/autoencoder/trainer.py
numalogic/models/autoencoder/variants/conv.py
numalogic/models/autoencoder/variants/lstm.py
numalogic/models/autoencoder/variants/transformer.py
numalogic/models/autoencoder/variants/vanilla.py
numalogic/postprocess.py
numalogic/preprocess/__init__.py
numalogic/preprocess/transformer.py
numalogic/registry/__init__.py
numalogic/registry/artifact.py
numalogic/registry/mlflow_registry.py
numalogic/synthetic/__init__.py
numalogic/synthetic/anomalies.py
numalogic/synthetic/sparsity.py
numalogic/synthetic/timeseries.py
numalogic/tools/callbacks.py
numalogic/tools/data.py
numalogic/tools/exceptions.py
numalogic/tools/types.py
pyproject.toml
tests/registry/test_mlflow_registry.py

- avoid logging RESOURCE_NOT_FOUND error
- add license info in source files (similar to numaflow)
- add slots to Registry classes to improve performance by 20%

chore: catch explicit model not found exception in mlflow

---

numalogic/config/__init__.py
numalogic/config/_config.py
numalogic/config/factory.py
numalogic/tools/exceptions.py
poetry.lock
pyproject.toml
tests/resources/config.yaml
tests/test_config.py

Introduce first version of config schema

feat: initial config schema

---

numalogic/config/factory.py
numalogic/models/threshold/__init__.py
numalogic/models/threshold/_static.py
tests/models/test_threshold.py

Introduce static threshold estimator

feat: static threshold estimator

---

docs/pre-processing.md
numalogic/config/factory.py
numalogic/preprocess/__init__.py
numalogic/preprocess/transformer.py
pyproject.toml
tests/preprocess/test_transformer.py

- Add tanh scaler
- Update documentation
- Add in config factory
- Bump version to v0.3.4

feat: tanh preprocessing

---

numalogic/registry/mlflow_registry.py
pyproject.toml
tests/registry/test_mlflow_registry.py

Fix transition function for moving models from one stage to another.

fix: transition

---

numalogic/models/autoencoder/trainer.py
numalogic/tools/callbacks.py
numalogic/tools/data.py
tests/models/autoencoder/test_trainer.py
tests/models/autoencoder/variants/test_conv.py
tests/tools/test_data.py

- fix validation loss run in trainer
- add docstrings to data module
- update unit tests
closes #150 #78

fix: validation loss not being logged

---

.github/workflows/ci.yml
pyproject.toml

chore!: drop support for python 3.8

---

pyproject.toml

Version update according to https://peps.python.org/pep-0440/

chore: fix version

---

numalogic/registry/mlflow_registry.py
numalogic/registry/redis_registry.py
tests/registry/test_mlflow_registry.py

Fix: Add caching debugging logs

fix: add caching logs

---

numalogic/tools/data.py
tests/tools/test_data.py

- fix StreamingDataset slicing
- add method to return full windowed data
- fix to just return the copy of the original array

fix: dataset slicing

---

udf/anomaly-detection/config/default-configs/config.yaml
udf/anomaly-detection/pyproject.toml
udf/anomaly-detection/src/_config.py
udf/anomaly-detection/src/_constants.py
udf/anomaly-detection/src/connectors/sentinel.py
udf/anomaly-detection/src/udf/inference.py
udf/anomaly-detection/src/udf/preprocess.py
udf/anomaly-detection/src/udf/threshold.py

1. Sentinel improvements
2. Model saving (fix for version number)

chore: improvements on sentinel and model saving

---

udf/anomaly-detection/src/connectors/sentinel.py

Redis conf

---

udf/anomaly-detection/src/udf/inference.py

fix: add more logs

---

docs/quick-start.md

fixed a few broken links that currently link to a File Not Found page.

doc: update quick-start.md

---

numalogic/udfs/entities.py
poetry.lock
pyproject.toml

add entities

---

numalogic/udfs/postprocess.py
numalogic/udfs/preprocess.py
numalogic/udfs/tools.py
tests/udfs/test_postprocess.py
tests/udfs/test_preprocess.py

feat: add postproc and threshold as PostProcessUDF

---

Dockerfile
numalogic/_constants.py
numalogic/config/__init__.py
numalogic/connectors/__init__.py
numalogic/udfs/__init__.py
numalogic/udfs/__main__.py
numalogic/udfs/_config.py
numalogic/udfs/factory.py
numalogic/udfs/inference.py
numalogic/udfs/postprocess.py
numalogic/udfs/preprocess.py
numalogic/udfs/trainer.py
requirements/requirements-torch.txt
tests/config/test_config.py
tests/udfs/resources/_config.yaml
tests/udfs/test_inference.py
tests/udfs/test_postprocess.py
tests/udfs/test_trainer.py

feat: load config from conf map

---

numalogic/udfs/entities.py
numalogic/udfs/postprocess.py
tests/udfs/resources/_config.yaml
tests/udfs/resources/_config2.yaml
tests/udfs/test_postprocess.py
tests/udfs/test_preprocess.py
tests/udfs/utility.py

1. Add publisher
2. Add test cases for preproc and postproc

fix: add publisher

---

numalogic/udfs/__init__.py

fix: config

---

numalogic/backtest/__init__.py
numalogic/backtest/__main__.py
numalogic/backtest/_clifunc.py
numalogic/backtest/_prom.py
numalogic/connectors/__init__.py
tests/test_backtest.py

- fix pydriud optional dependency import
- minor module level import fix

fix: allow full df scores in backtest

---

numalogic/udfs/_base.py
numalogic/udfs/factory.py
numalogic/udfs/inference.py
numalogic/udfs/postprocess.py
numalogic/udfs/preprocess.py
numalogic/udfs/trainer.py
poetry.lock
pyproject.toml
tests/udfs/test_factory.py
tests/udfs/test_inference.py
tests/udfs/test_numaflow.py
tests/udfs/test_postprocess.py
tests/udfs/test_preprocess.py
tests/udfs/test_trainer.py
tests/udfs/utility.py

- upgrade pynumaflow version
- improve test coverage
- downgrade moto library to fix test failures

chore: upgrade pynumaflow version to v0.5

---

poetry.lock
pyproject.toml

fix: point to Chichu's fork for pydruid

fix:  pydruid version update

---

pyproject.toml

Update TOML version for druid changes

upgrade version

---

numalogic/connectors/_config.py
numalogic/tools/types.py
numalogic/udfs/trainer.py
pyproject.toml
tests/udfs/resources/_config2.yaml
tests/udfs/test_trainer.py

Update config to support multiple DruidFetcher

add: druidfetcher support for different configId

---

numalogic/connectors/prometheus.py
numalogic/udfs/_base.py
numalogic/udfs/inference.py
numalogic/udfs/postprocess.py
numalogic/udfs/preprocess.py
numalogic/udfs/trainer.py
tests/connectors/test_prometheus.py

- add support for multivariate prometheus fetcher
- add generic methods to base udf class

feat: support multivar prom

---

numalogic/backtest/_prom.py
numalogic/monitoring/metrics.py
numalogic/udfs/README.md
numalogic/udfs/_metrics.py
numalogic/udfs/inference.py
numalogic/udfs/postprocess.py
numalogic/udfs/preprocess.py
numalogic/udfs/tools.py

Demo branch

---

numalogic/_constants.py
numalogic/config/_config.py
numalogic/monitoring/metrics.py
numalogic/tools/types.py
numalogic/udfs/README.md
numalogic/udfs/_metrics.py
numalogic/udfs/entities.py
numalogic/udfs/inference.py
numalogic/udfs/postprocess.py
numalogic/udfs/preprocess.py
numalogic/udfs/tools.py
numalogic/udfs/trainer/_base.py
numalogic/udfs/trainer/_druid.py
numalogic/udfs/trainer/_prom.py
pyproject.toml
tests/udfs/resources/_config2.yaml
tests/udfs/test_trainer.py

1. Add source tags for the metrics
2. Fix some logs

"Source" tag for metrics

---

numalogic/udfs/inference.py
numalogic/udfs/payloadtx.py
numalogic/udfs/postprocess.py
numalogic/udfs/preprocess.py
numalogic/udfs/staticthresh.py
numalogic/udfs/tools.py
numalogic/udfs/trainer/_base.py
numalogic/udfs/trainer/_druid.py
numalogic/udfs/trainer/_prom.py

logging fix

---

numalogic/connectors/_config.py
numalogic/connectors/druid/_druid.py
numalogic/udfs/trainer/_druid.py
pyproject.toml

Static filter

---

numalogic/connectors/druid/_druid.py
tests/connectors/test_druid.py

Implemented pivot with multiple columns in druid connector

feat: multi column pivot for druid connector

---

numalogic/config/_config.py
numalogic/udfs/postprocess.py
pyproject.toml
tests/connectors/test_druid.py
tests/udfs/test_postprocess.py

Support for None for postproc.

Postproc support for None

---

numalogic/connectors/druid/_druid.py
pyproject.toml

Changing pivot to pivot_table to support aggregation

Fix: Changing pivot to pivot_table to support aggregation

---

numalogic/connectors/_config.py
numalogic/connectors/druid/_druid.py
pyproject.toml
tests/connectors/test_druid.py

Adding agg to pivot config for multi pivot

feat: agg from conf for multi pivot

---

numalogic/connectors/_config.py

fix: make pivot as optional

---

pyproject.toml

fix: release new patch version

fix: release new patch version

---

.github/workflows/release.yml

This is related to issue : https://github.intuit.com/oss-analytics/AIOps-project/issues/186
Adding job in github workflow to build RDS image

Adding job in github workflow to build RDS image

---

docs/ml-flow.md
examples/multi_udf/src/udf/train.py
numalogic/registry/mlflow_registry.py
tests/registry/test_mlflow_registry.py

1. Support artifact-type in mlflow registry from user.
2. Update docs

fix: support all sklearn classes
