numaproj/numalogic

.github/workflows/ci.yml, .github/workflows/coverage.yml, .github/workflows/lint.yml, .github/workflows/pypi.yml, Makefile, README.md, numalogic/registry/__init__.py, numalogic/tests/registry/_mlflow_utils.py, numalogic/tools/types.py, poetry.lock, pyproject.toml
`mlflow` will be an optional requirement for numalogic.
If the user wants to install mlflow, they can do so by:
`pip install numalogic[mlflow]`
or,
`poetry install -E mlflow`
=> chore!: make mlflow as an optional dependency

numalogic/models/autoencoder/pipeline.py
Fixes #59 
Signed-off-by: Reeti Sarup <reeti.sarup@gmail.com>
**Explain what this PR does:**
Adding docstrings for the `SparseAEPipeline` class & its methods in the `models/autoencoder/pipeline.py` file.
=> docs: adding docstrings for the SparseAEPipeline class

docs/quick-start.md, examples/numalogic-simple-pipeline/Dockerfile, examples/numalogic-simple-pipeline/poetry.lock, examples/numalogic-simple-pipeline/pyproject.toml, examples/numalogic-simple-pipeline/src/utils.py, poetry.lock, pyproject.toml
Change the MLFlow port to point to `default` namespace.
=> fix: change example pipeline mlflow port

.github/workflows/ci.yml, .github/workflows/coverage.yml, .github/workflows/gh-pages.yaml, .github/workflows/lint.yml, .gitignore, poetry.lock, pyproject.toml
This to avoid the vulnerability in torch 1.12.1
=> fix: Upgrade torch to 1.13.1

docs/quick-start.md, numalogic/models/threshold/_static.py, numalogic/models/threshold/_std.py, tests/models/test_threshold.py
=> fix!: consistency with threshold methods

numalogic/preprocess/transformer.py, pyproject.toml, tests/preprocess/test_transformer.py
When the variance of input time series is zero, then we encounter a division by zero problem.
This led to NaN outputs.
This change checks if a feature is indistinguishable from a constant feature or not. If yes, then set the std as 1.0 for that feature. This will stop the feature from getting scaled by it's zero variance.
=> fix: Tanhscaler nan output for constant feature

docs/ml-flow.md, numalogic/registry/mlflow_registry.py, numalogic/tools/types.py, poetry.lock, pyproject.toml, tests/registry/test_mlflow_registry.py
Helps for a better config-driven registry instance creation.
- Avoid specifying mlflow instance type in the constructor
- Detect the correct handler during save
- Specify artifact type during load
- Update docs
=> chore!: Auto detect instance type while mlflow model save

Makefile, docs/post-processing.md, docs/pre-processing.md, docs/quick-start.md, examples/numalogic-simple-pipeline/src/udf/postprocess.py, examples/numalogic-simple-pipeline/src/udf/preprocess.py, examples/numalogic-simple-pipeline/src/udf/train.py, numalogic/__init__.py, numalogic/base.py, numalogic/config/factory.py, numalogic/models/autoencoder/base.py, numalogic/models/forecast/variants/naive.py, numalogic/models/threshold/_static.py, numalogic/models/threshold/_std.py, numalogic/registry/redis_registry.py, numalogic/tools/__init__.py, numalogic/tools/types.py, numalogic/transforms/__init__.py, numalogic/transforms/_movavg.py, numalogic/transforms/_postprocess.py, numalogic/transforms/_scaler.py, numalogic/transforms/_stateless.py, poetry.lock, pyproject.toml, tests/__init__.py, tests/config/test_config.py, tests/transforms/test_postprocess.py, tests/transforms/test_transforms.py
- Move preprocess and postprocess files & modules -> transforms
- Avoid setting up handler in loggers
- Add base classes for extensibility
Note: Coverage is failing due to some other network issue, not related to the PR.
=> chore!: refactor preproc and postproc into transforms module

numalogic/__init__.py, numalogic/registry/redis_registry.py, pyproject.toml
=> fix: removing logger level setting

.github/workflows/ci.yml, pyproject.toml
Signed-off-by: tcchawla [tc.chawla2000@gmail.com](mailto:tc.chawla2000@gmail.com)
Solves issue: #68 
This PR adds support for latest python 3.11 version
Changed workflow to support the latest version
Changed project dependency to support 3.11.x versions
Please close #72, as this is extension of the same PR
=> Upgraded python support for 3.11

numalogic/registry/artifact.py, numalogic/registry/dynamodb_registry.py, numalogic/registry/localcache.py, numalogic/registry/redis_registry.py, numalogic/tools/data.py, tests/registry/test_cache.py, tests/registry/test_redis_registry.py
- fix cache key overwrite issue which caused a stale model to persist for a long time
- Save sourcetype in artifact data extras to be used for other logic
- Improve docs
=> fix (RedisRegistry): avoid overwriting cache with the same key during load 

udf/anomaly-detection/poetry.lock, udf/anomaly-detection/pyproject.toml, udf/anomaly-detection/src/udf/threshold.py
=> chore: allow python 3.9 to 3.12

.github/workflows/ci.yml, .github/workflows/coverage.yml, .github/workflows/pypi.yml, numalogic/config/factory.py, numalogic/models/threshold/__init__.py, numalogic/models/threshold/_mahalanobis.py, numalogic/registry/dynamodb_registry.py, poetry.lock, tests/models/test_threshold.py
Introduce a Multivariate thresholding technique using Mahalanobis distance and Chebyshev's inequality.
Comparison added here: https://github.com/numaproj/numalogic-benchmarks/pull/2
=> feat: Multivariate threshold using Mahalanobis distance

udf/anomaly-detection/src/udf/inference.py, udf/anomaly-detection/src/udf/preprocess.py, udf/anomaly-detection/src/udf/threshold.py
Exception Handling while loading models.
=> Exception fix

numalogic/registry/_serialize.py, pyproject.toml, tests/registry/test_serialize.py
- close the buffer
- use highest pickle protocol by default
- benchmarking in unit tests
|   Change	|   Improvement	|
|---	|---	|
|  Closing buffer 	|   3.2%	|
|  Protocol update 	|   15.5%	|
=> perf: improve serialization performance

numalogic/connectors/druid.py
Using dimensions as a list of strings causes ambiguity in other druid clients. Well-defined dimensions makes use of the utility in pydruid to create dimensions as DimensionSpec. This helps with deterministic serialization and de-serialization of the query.
=> feat: use well-defined dimensions instead of strings

Makefile, numalogic/udfs/__main__.py, poetry.lock, pyproject.toml, tests/udfs/test_main.py
- add unit tests 
- bump version
- make tag
=> fix: udf server start error

Dockerfile, pyproject.toml
Fix dockerfile arg scope issue where extra args were not getting installed
=> fix: docker extra args error

numalogic/config/_config.py, numalogic/connectors/_config.py, numalogic/registry/artifact.py, numalogic/registry/localcache.py, numalogic/registry/redis_registry.py, numalogic/tools/exceptions.py, numalogic/udfs/_config.py, numalogic/udfs/inference.py, numalogic/udfs/postprocess.py, numalogic/udfs/preprocess.py, numalogic/udfs/trainer.py, pyproject.toml, tests/config/test_optdeps.py, tests/registry/test_cache.py, tests/registry/test_redis_registry.py, tests/udfs/test_trainer.py
1. Add jitter
-  for caches
-  for model saving
2. Support RegistryConf and JitterConf
=> feat: add jitter

numalogic/config/_config.py, numalogic/udfs/inference.py, numalogic/udfs/tools.py, numalogic/udfs/trainer.py, pyproject.toml, tests/udfs/test_trainer.py
Tackling retraining for insufficient data.
=> add retrain logic for insufficient data

numalogic/config/_config.py, numalogic/udfs/tools.py, numalogic/udfs/trainer/_base.py, tests/udfs/resources/_config.yaml, tests/udfs/resources/_config2.yaml
=> fix: add max value map for cliping the value

numalogic/udfs/postprocess.py, poetry.lock
take mean before calculating the thresholds
=> fix: take mean before calculating the thresholds

numalogic/udfs/trainer/_base.py, pyproject.toml, tests/udfs/test_trainer.py
=> Fix: Get metrics from _conf.metrics on Trainer to avoid issue with Flattening the matrix

numalogic/config/_config.py, numalogic/tools/data.py, numalogic/udfs/postprocess.py, numalogic/udfs/trainer/_base.py, tests/tools/test_data.py
Useful for flattened vectored data
=> feat: introduce stride in dataset

numalogic/udfs/postprocess.py, numalogic/udfs/preprocess.py, numalogic/udfs/tools.py, numalogic/udfs/trainer/_base.py, tests/udfs/test_trainer.py
Observe UDF logs and optimize as much possible.
=> Optimize UDF logs

numalogic/udfs/__main__.py, numalogic/udfs/inference.py, numalogic/udfs/payloadtx.py, numalogic/udfs/postprocess.py, numalogic/udfs/preprocess.py, numalogic/udfs/staticthresh.py, numalogic/udfs/tools.py, numalogic/udfs/trainer/_base.py, numalogic/udfs/trainer/_druid.py, numalogic/udfs/trainer/_prom.py, numalogic/udfs/trainer/_rds.py, pyproject.toml, tests/udfs/test_payloadtx.py
1. Make metrics disabled by default
2. Fix transformer Payload bug.
3. Add Test case for Payload Transformer vertex
=> fix: add test cases for payload Transformer

numalogic/udfs/_metrics_utility.py, numalogic/udfs/trainer/_druid.py, pyproject.toml
=> fix: bug in metric call

numalogic/udfs/inference.py, numalogic/udfs/preprocess.py
What: Observed `NoneType: None ` in preprocess and inference UDFs. Example: 
`2024-07-02 03:44:26,863 - 139658258261696 - ERROR - uuid='2a4ae443-15ab-496c-95ba-83ebc380df59' event='Artifact model not loaded!' udf_vertex='inference' config_id='serviceTraceMetrics' pipeline_id='request' metadata={'adjust_with_impact': {'timestamp': 1719891659999, 'true': 0}, 'mean_of_features': {'true': 0.23076923076923078}, 'numalogic_opex_tags': {'source': 'numalogic_metrics'}, 'tags': {'assetAlias': 'Intuit.cto.iam.iux', 'assetId': '3172803529671879897', 'env': 'prd', 'opname': 'GET /fe_logger/.env.dev.local'}} exc_info=True level='error' timestamp='2024-07-02T03:44:26.863733Z'
NoneType: None`
Why: logger.exception is usually called from the `except` block. Not logging from the except block, means there …
=> fix for Nonetype: None in the ERROR logs

numalogic/base.py, numalogic/registry/mlflow_registry.py, pyproject.toml, tests/registry/_mlflow_utils.py
The transformers and threshold model inherit BaseEstimator class.
Fixes:
> mlflow saving of models
=> fix: support sklearn BaseEstimators

numalogic/connectors/__init__.py, numalogic/connectors/wavefront.py, numalogic/tools/exceptions.py, poetry.lock, pyproject.toml, tests/connectors/test_wf.py
Introducing a wavefront data fetcher.
Supports simple metric based queries as well as raw queries.
=> feat: wavefront fetcher

numalogic/registry/mlflow_registry.py, pyproject.toml, tests/registry/test_mlflow_registry.py
There existed errors in test logs while test cases still passed. One example is the ConnectionError due to not mocking mlflow function calls properly.
Fixed through modifying a few syntax for patch mock calls. The test cases should pass with no logging errors now.
=> fix: test cases mlflow registry

.gitignore, numalogic/registry/mlflow_registry.py, pyproject.toml, tests/registry/_mlflow_utils.py, tests/registry/test_mlflow_registry.py
1. Implemented save_multiple and load_multiple for mlflow registry
2. Test cases for implementation.
=> Implement: multiple save and load for mlflow registry
